import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Landing
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Signin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/reserve" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Reserve
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/profile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboardtwentyfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DashboardTwentyFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/employee" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Employee
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboardtwenty" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DashboardTwenty
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboardfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DashboardFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Dashboard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signinup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Signinup
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboardtwentyone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DashboardTwentyOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dashboardtwentythree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DashboardTwentyThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/employeeone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EmployeeOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Admin
          </Link>
        </li>
        {/* ... (rest of the list items) */}
      </ul>
    </div>
  );
};

export default Home;